from __future__ import annotations

# Canonical intent list proposed for the finetuned DistilBERT model.
CANONICAL_INTENTS: list[str] = [
    # Payments
    "send_money",
    "request_money",
    "split_bill",
    "scan_and_pay",
    "pay_merchant",
    "bank_transfer",
    "self_transfer",
    # Bills & Recharge
    "recharge_mobile",
    "pay_electricity_bill",
    "pay_water_bill",
    "pay_gas_bill",
    "pay_internet_bill",
    "pay_dth_bill",
    "pay_subscription",
    "pay_credit_card_bill",
    "pay_rent",
    # Account Management
    "check_balance",
    "view_transactions",
    "view_last_transaction",
    "account_statement",
    "add_bank_account",
    "remove_bank_account",
    "link_upi",
    "unlink_upi",
    "change_upi_pin",
    "reset_upi_pin",
    "check_reward_balance",
    # Subscriptions
    "cancel_subscription",
    "pause_subscription",
    "renew_subscription",
    "autopay_setup",
    "autopay_cancel",
    "schedule_payment",
    # Customer Support
    "refund_request",
    "track_refund",
    "dispute_transaction",
    "report_failed_payment",
    "raise_chargeback",
    "payment_status_query",
    # Security
    "block_card",
    "unblock_card",
    "freeze_wallet",
    "unfreeze_wallet",
    "report_fraud",
    "suspicious_transaction_query",
    # Wealth
    "investment_query",
    "mutual_fund_query",
    "loan_query",
    "insurance_query",
    "emi_query",
    # Generic
    "find_nearest_merchant",
    "offers_query",
    "cashback_query",
    "help_query",
    # Safety fallback
    "unknown",
]


# Minimal required entities by intent.
# Keep this conservative; downstream agent can ask clarifying questions.
REQUIRED_FIELDS_BY_INTENT: dict[str, list[str]] = {
    "send_money": ["amount", "recipient"],
    "request_money": ["amount", "recipient"],
    "split_bill": ["amount"],
    "scan_and_pay": ["amount"],
    "pay_merchant": ["amount", "merchant_name"],
    "bank_transfer": ["amount", "beneficiary_account"],
    "self_transfer": ["amount", "from_account", "to_account"],
    "recharge_mobile": ["phone"],
    "pay_electricity_bill": ["biller_id"],
    "pay_water_bill": ["biller_id"],
    "pay_gas_bill": ["biller_id"],
    "pay_internet_bill": ["biller_id"],
    "pay_dth_bill": ["biller_id"],
    "pay_subscription": ["subscription_id"],
    "pay_credit_card_bill": ["card_last4"],
    "pay_rent": ["amount", "recipient"],
    "check_balance": [],
    "view_transactions": [],
    "view_last_transaction": [],
    "account_statement": [],
    "add_bank_account": ["account_number", "ifsc"],
    "remove_bank_account": ["account_ref"],
    "link_upi": ["upi_id"],
    "unlink_upi": ["upi_id"],
    "change_upi_pin": [],
    "reset_upi_pin": [],
    "check_reward_balance": [],
    "cancel_subscription": ["subscription_id"],
    "pause_subscription": ["subscription_id"],
    "renew_subscription": ["subscription_id"],
    "autopay_setup": ["payee_ref"],
    "autopay_cancel": ["autopay_id"],
    "schedule_payment": ["amount", "schedule_at"],
    "refund_request": ["transaction_ref"],
    "track_refund": ["refund_ref"],
    "dispute_transaction": ["transaction_ref"],
    "report_failed_payment": ["transaction_ref"],
    "raise_chargeback": ["transaction_ref"],
    "payment_status_query": ["transaction_ref"],
    "block_card": ["card_last4"],
    "unblock_card": ["card_last4"],
    "freeze_wallet": [],
    "unfreeze_wallet": [],
    "report_fraud": ["transaction_ref"],
    "suspicious_transaction_query": [],
    "investment_query": [],
    "mutual_fund_query": [],
    "loan_query": [],
    "insurance_query": [],
    "emi_query": [],
    "find_nearest_merchant": ["category"],
    "offers_query": [],
    "cashback_query": [],
    "help_query": [],
    "unknown": ["intent"],
}


INTENT_ALIASES: dict[str, str] = {
    "balance_query": "check_balance",
    "recharge": "recharge_mobile",
    "book_service": "help_query",
    "transaction_history": "view_transactions",
    "recharge_plans_query": "offers_query",
}
